### ISSUE TITLE
Deleting component does not delete its interfaces

### ISSUE THREAD

**Issue by tlmrgvf** [ccims/ccims-backend-gql#47]
To reproduce:
- Create component
- Create interface for component
- Delete component

The component will be deleted, the interface will not.
Is this intentional?

**Comment by nk-coding** [comment]
definitly a bug  
forgot to mark the interfaces as deleted  
will fix it later today together with some other non-cascding delete bugs

**Comment by nk-coding** [comment]
fixed with ea54acda398d4628aa76c356d871fd015159438b  
sry for the delay
